<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Model;

use CreditNote\Model\Base\OrderCreditNote as BaseOrderCreditNote;

/**
 * Class OrderCreditNote
 * @package CreditNote\Model
 */
class OrderCreditNote extends BaseOrderCreditNote
{
}
