<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Form\Type;

use CreditNote\Form\Type\Base\OrderCreditNoteIdType as BaseOrderCreditNoteIdType;

/**
 * Class OrderCreditNote
 * @package CreditNote\Form
 */
class OrderCreditNoteIdType extends BaseOrderCreditNoteIdType
{
}
