<?php

declare(strict_types=1);

namespace CreditNote\Model\Map;

/**
 * The one constant of the Propel table map the listener reads. The real map is generated by
 * the shop kernel, which the unit suite does not boot: this stub is loaded by a unit test only
 * when the generated class is not available.
 */
final class CreditNoteTableMap
{
    public const TABLE_NAME = 'credit_note';
}
