<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Event;

use CreditNote\Event\Base\OrderCreditNoteEvent as BaseOrderCreditNoteEvent;

/**
 * Class OrderCreditNoteEvent
 * @package CreditNote\Event
 */
class OrderCreditNoteEvent extends BaseOrderCreditNoteEvent
{
}
