<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Form\Base;

use CreditNote\CreditNote;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class OrderCreditNoteCreateForm
 * @package CreditNote\Form\Base
 * @author TheliaStudio
 */
class OrderCreditNoteCreateForm extends BaseForm
{
    const FORM_NAME = "order_credit_note_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addOrderIdField($translationKeys, $fieldsIdKeys);
        $this->addAmountField($translationKeys, $fieldsIdKeys);
        $this->addMessageField($translationKeys, $fieldsIdKeys);
        $this->addCouponIdField($translationKeys, $fieldsIdKeys);
    }

    protected function addOrderIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("order_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("order_id", $translationKeys), [], CreditNote::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("order_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addAmountField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("amount", "number", array(
            "label" => $this->translator->trans($this->readKey("amount", $translationKeys), [], CreditNote::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("amount", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
                "step" => "0.01",
            )
        ));
    }

    protected function addMessageField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("message", "textarea", array(
            "label" => $this->translator->trans($this->readKey("message", $translationKeys), [], CreditNote::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("message", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addCouponIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("coupon_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("coupon_id", $translationKeys), [], CreditNote::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("coupon_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "order_id" => "order_credit_note_order_id",
            "amount" => "order_credit_note_amount",
            "message" => "order_credit_note_message",
            "coupon_id" => "order_credit_note_coupon_id",
        );
    }
}
