<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Loop;

use CreditNote\Loop\Base\OrderCreditNote as BaseOrderCreditNoteLoop;

/**
 * Class OrderCreditNote
 * @package CreditNote\Loop
 */
class OrderCreditNote extends BaseOrderCreditNoteLoop
{
    /**
     * You may now add your own logic
     */
}
