<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Form;

use CreditNote\Form\Base\OrderCreditNoteCreateForm as BaseOrderCreditNoteCreateForm;

/**
 * Class OrderCreditNoteCreateForm
 * @package CreditNote\Form
 */
class OrderCreditNoteCreateForm extends BaseOrderCreditNoteCreateForm
{
    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder->remove("coupon_id");
    }

    public function getTranslationKeys()
    {
        return array(
            "order_id" => "Order id",
            "amount" => "Amount",
            "message" => "Message",
            "coupon_id" => "Coupon id",
        );
    }
}
