<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use CreditNote\Model\OrderCreditNoteQuery;

/**
 * Class OrderCreditNote
 * @package CreditNote\Form\Base
 * @author TheliaStudio
 */
class OrderCreditNoteIdType extends AbstractIdType
{
    const TYPE_NAME = "order_credit_note_id";

    protected function getQuery()
    {
        return new OrderCreditNoteQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
