<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace CreditNote\Controller;

use CreditNote\Controller\Base\CreditNoteConfigController as BaseCreditNoteConfigController;

/**
 * Class CreditNoteConfigController
 * @package CreditNote\Controller
 */
class CreditNoteConfigController extends BaseCreditNoteConfigController
{
}
