<?php

declare(strict_types=1);

namespace CreditNote\Tests\Unit;

use CreditNote\Event\CreditNoteEvents;
use CreditNote\EventListener\CreditNoteListener;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * The numbering listener is wired on the Propel events the credit note model dispatches
 * through ModelEventDispatcherTrait: a reference before the insert, the counter after it,
 * the accounting number when the status changes.
 *
 * The Propel map class the listener reads the table name from is generated by the shop
 * kernel, which the unit suite does not boot: a stub carrying that constant stands in.
 */
final class CreditNoteListenerTest extends TestCase
{
    private const TABLE = 'credit_note';

    public static function setUpBeforeClass(): void
    {
        if (!class_exists(\CreditNote\Model\Map\CreditNoteTableMap::class)) {
            require \dirname(__DIR__) . '/Support/Stub/CreditNoteTableMap.php';
        }
    }

    #[Test]
    public function theListenerNumbersTheCreditNoteAroundItsPropelEvents(): void
    {
        $subscriptions = CreditNoteListener::getSubscribedEvents();

        self::assertSame(['generateCreditNoteRef', 128], $subscriptions[CreditNoteEvents::preInsert(self::TABLE)]);
        self::assertSame(['incrementCreditNoteRef', 128], $subscriptions[CreditNoteEvents::postInsert(self::TABLE)]);
        self::assertSame(['generateCreditNoteInvoiceRef', 128], $subscriptions[CreditNoteEvents::preUpdate(self::TABLE)]);

        foreach ($subscriptions as $eventName => [$method]) {
            self::assertStringStartsWith('credit-note.', $eventName);
            self::assertStringEndsWith('.credit_note', $eventName);
            self::assertTrue(method_exists(CreditNoteListener::class, $method), \sprintf('%s is a method of the listener', $method));
        }
    }

    #[Test]
    public function theEventNamesCarryTheTableTheyAreDispatchedFor(): void
    {
        self::assertSame('credit-note.pre.insert.credit_note', CreditNoteEvents::preInsert('credit_note'));
        self::assertSame('credit-note.post.insert.credit_note_detail', CreditNoteEvents::postInsert('credit_note_detail'));
        self::assertSame('credit-note.pre.update.credit_note', CreditNoteEvents::preUpdate('credit_note'));
        self::assertSame('credit-note.post.update.credit_note', CreditNoteEvents::postUpdate('credit_note'));
        self::assertSame('credit-note.pre.delete.credit_note', CreditNoteEvents::preDelete('credit_note'));
        self::assertSame('credit-note.post.delete.credit_note', CreditNoteEvents::postDelete('credit_note'));
    }
}
